#!/bin/sh

DRY_RUN=false

RELEASE_BRANCH=master
RELEASE_VERSION_CODE=33
RELEASE_VERSION=0.6.7
NEXT_DEV_VERSION=0.7-SNAPSHOT

echo "DRY_RUN:              $DRY_RUN"
echo "RELEASE_BRANCH:       $RELEASE_BRANCH"
echo "RELEASE_VERSION_CODE: $RELEASE_VERSION_CODE"
echo "RELEASE_VERSION:      $RELEASE_VERSION"
echo "NEXT_DEV_VERSION:     $NEXT_DEV_VERSION"
